apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Houssemeddine-ziadi/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

